// Main file for obfuscator
// Code line 1
int var_1 = 1;
// Code line 2
int var_2 = 2;
// Code line 3
int var_3 = 3;
// Code line 4
int var_4 = 4;
// Code line 5
int var_5 = 5;
// Code line 6
int var_6 = 6;
// Code line 7
int var_7 = 7;
// Code line 8
int var_8 = 8;
// Code line 9
int var_9 = 9;
// Code line 10
int var_10 = 10;
